-- you must insert after create entity

INSERT INTO `applestore`.`categories` (`name`) VALUES ('Mac');
INSERT INTO `applestore`.`categories` (`name`) VALUES ('Ipad');
INSERT INTO `applestore`.`categories` (`name`) VALUES ('Iphone');

INSERT INTO `applestore`.`products` (`description`, `image_url`, `name`, `price`, `weight`, `category_id`) VALUES ('Our thinnest, lightest notebook, completely transformed by the Apple M1 chip. CPU speeds up to 3.5x faster. GPU speeds up to 5x faster. ', 'https://res.cloudinary.com/dridw8v4v/image/upload/v1641301734/macbook-air-space-gray_m654cn.jpg', 'MacBook Air', '999', '1290', '1');
INSERT INTO `applestore`.`products` (`description`, `image_url`, `name`, `price`, `weight`, `category_id`) VALUES ('Liquid Retina display', 'https://res.cloudinary.com/dridw8v4v/image/upload/v1641301734/ipad-pro-12-select-202003_bgkxww.png', 'IPad Pro 12.9 inch', '535', '641', '2');
INSERT INTO `applestore`.`products` (`description`, `image_url`, `name`, `price`, `weight`, `category_id`) VALUES ('The iPhone 12 mini is the smallest of four iPhone models Apple revealed in its October 2020 "Hi, Speed" event. It has a 5.4-inch Super Retina XDR display, the A14 Bionic processor, and a dual-camera system.', 'https://res.cloudinary.com/dridw8v4v/image/upload/v1644984056/dwubfs8a8mnbw8tdiba7.png', 'IPhone 12 mini', '699', '133', '3');
INSERT INTO `applestore`.`products` (`description`, `image_url`, `name`, `price`, `weight`, `category_id`) VALUES ('Iphone 11', 'https://res.cloudinary.com/dridw8v4v/image/upload/v1641301733/iphone11_mivqsd.jpg', 'IPhone 11 64Gb', '599', '194', '3');
INSERT INTO `applestore`.`products` (`description`, `image_url`, `name`, `price`, `weight`, `category_id`) VALUES ('iPhone SE packs our powerful A13 Bionic chip into our most popular size at our most affordable price. It’s just what you’ve been waiting for.', 'https://res.cloudinary.com/dridw8v4v/image/upload/v1641301733/iphone-se-family-select-2020_ww0vjb.jpg', 'IPhone SE 64Gb', '399', '148', '3');
INSERT INTO `applestore`.`products` (`description`, `image_url`, `name`, `price`, `weight`, `category_id`) VALUES ('this is macbook', 'https://res.cloudinary.com/dridw8v4v/image/upload/v1641301733/mbp16touch-space-select-201911_mxmd75.jpg', 'MacBook Pro 16\"', '2399', '2000', '1');
INSERT INTO `applestore`.`products` (`description`, `image_url`, `name`, `price`, `weight`, `category_id`) VALUES ('Ceramic Shield front Glass back and aluminum design', 'https://res.cloudinary.com/dridw8v4v/image/upload/v1642989817/item_3718534_679_lq2x27.jpg','Iphone 13', '1190', '149', '3');
INSERT INTO `applestore`.`products` (`description`, `image_url`, `name`, `price`, `weight`, `category_id`) VALUES ('13.3-inch (diagonal) LED-backlit display with IPS technology; 2560-by-1600 native resolution at 227 pixels per inch with support for millions of colors','https://res.cloudinary.com/dridw8v4v/image/upload/v1642990753/apple-macbook-air-2020-m1-mgn93_df20ee70_fhwjha.webp','MacBook Air 2020','890','1300', '1');
INSERT INTO `applestore`.`products` (`description`, `image_url`, `name`, `price`, `weight`, `category_id`) VALUES ('Supercharged for pros', 'https://res.cloudinary.com/dridw8v4v/image/upload/v1642990584/t%E1%BA%A3i_xu%E1%BB%91ng_hxnarb.jpg','MacBook Pro 16" 2022', '2900', '1450','1');
INSERT INTO `applestore`.`products` (`description`, `image_url`, `name`, `price`, `weight`, `category_id`) VALUES ('10.9 inches (280 mm) (2,360 x 1,640) px (264 ppi), 500-nits Max Brightness','https://res.cloudinary.com/dridw8v4v/image/upload/v1642991026/40641_ipad_air_4_10_9_inch_wifi_rose_ha1_sz61t5.jpg','Ipad Air 4', '799', '340','2');
INSERT INTO `applestore`.`products` (`description`, `image_url`, `name`, `price`, `weight`, `category_id`) VALUES ('IPS LCD, 120Hz, 600 nits (typ)','https://res.cloudinary.com/dridw8v4v/image/upload/v1642991126/ipad-pro-11-inch-2020-xam-600x600-200x200_a0rxaj.jpg','Ipad Pro 2020', '890','350','2');
INSERT INTO `applestore`.`products` (`description`, `image_url`, `name`, `price`, `weight`, `category_id`) VALUES ('The ultimate iPad experience. Now with breakthrough M1 performance, a breathtaking XDR display, and blazing‑fast 5G wireless. Buckle up.','https://res.cloudinary.com/dridw8v4v/image/upload/v1642991356/11_wlf7c6.png','Ipad Pro M1','600','250','2');

INSERT INTO `applestore`.`roles` (`name`) VALUES ('ROLE_ADMIN');
INSERT INTO `applestore`.`roles` (`name`) VALUES ('ROLE_USER');
